MegaInventory.Web/Controllers/ProductController.cs
using MegaInventory.BLL.DTO;
using MegaInventory.BLL.Shared.Requests;
using MegaInventory.ShopService.Services.Interface;
using MegaInventory.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static MegaInventory.BLL.Shared.Dictionaries;

namespace MegaInventory.Web.Controllers
{
    public class ProductController : BaseController
    {
        public ProductController(IStoreService storeService, IConfiguration configuration) : base(storeService, configuration)
        {

        }
        public IActionResult Index()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new ProductDTO
                {
                    Product = new BLL.Entities.Product
                    {
                        ProductDescription = model.Description,
                        ProductSKU = model.SKU,
                        ProductPurchasePrice = model.PurchasePrice,
                        ProductSellingPrice = model.SalePrice
                    }
                };
                var request = Request<ProductDTO>.CreateRequest(product, ApiKey, Operation.Insert.ToString());
                var result = await _storeService.AddProduct(request);
                if (result.IsSuccess)
                {
                   return RedirectToAction("Index", "Home");
                }
                return View();
            }
            return View();
        }
    }
}

MegaInventory.Web/Controllers/SalesOrderController.cs
using MegaInventory.BLL.DTO;
using MegaInventory.BLL.Shared.Requests;
using MegaInventory.ShopService.Services.Interface;
using MegaInventory.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static MegaInventory.BLL.Shared.Dictionaries;

namespace MegaInventory.Web.Controllers
{
    public class SalesOrderController : BaseController
    {
        public SalesOrderController(IStoreService storeService, IConfiguration configuration) : base(storeService, configuration)
        {

        }
        public IActionResult Index()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(SalesOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var warehouse = new SalesOrderDTO
                {
                    SalesOrder = new BLL.Entities.SalesOrder
                    {
                        SalesOrderInventoryLocationID =1,
                        SalesOrderClientId = model.ClientId,
                        SalesOrderStatus = "Verified",
                        SalesOrderDetails = new List<BLL.Entities.SalesOrderDetail>
                        {
                            new BLL.Entities.SalesOrderDetail
                            {
                                 SalesOrderRowProductSku = model.ProductSku,
                                 SalesOrderRowUnitPriceWithoutTaxOrDiscount = model.GrossPrice,
                                 SalesOrderRowQuantity = model.Quantity,
                                 SalesOrderRowShippedQuantity =0,
                                 SalesOrderRowTotalAmount = model.NetPrice,
                                 SalesOrderRowTotalDiscountAmount = model.DiscountAmount,
                                 SalesOrderTotalTaxAmount = model.TaxAmount
                            }
                        }


                    }
                };
                var request = Request<SalesOrderDTO>.CreateRequest(warehouse, ApiKey, Operation.Insert.ToString());
                var result = await _storeService.AddSalesOrder(request);
                if (result.IsSuccess)
                {
                    return RedirectToAction("Index", "Home");
                }
                return View();
            }
            return View();
        }
    }
}

MegaInventory.Web/Controllers/WarehouseController.cs
using MegaInventory.BLL.DTO;
using MegaInventory.BLL.Shared.Requests;
using MegaInventory.ShopService.Services.Interface;
using MegaInventory.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static MegaInventory.BLL.Shared.Dictionaries;

namespace MegaInventory.Web.Controllers
{
    public class WarehouseController : BaseController
    {
        public WarehouseController(IStoreService storeService, IConfiguration configuration ) : base(storeService, configuration)
        {

        }
        public IActionResult Index()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(WareHouseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var warehouse = new WarehouseDTO
                {
                    Warehouse = new BLL.Entities.Warehouse
                    {
                        InventoryLocationAbbreviation = model.Abbreviation,
                        InventoryLocationAddress = model.Address,
                        InventoryLocationName = model.Name
                    }
                };
                var request = Request<WarehouseDTO>.CreateRequest(warehouse,ApiKey, Operation.InsertOrUpdate.ToString());
                var result = await _storeService.AddOrUpdateWarehouse(request);
                if (result.IsSuccess)
                {
                    return RedirectToAction("Index", "Home");
                }
                return View();
            }
            return View();
        }
    }
}

MegaInventory.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MegaInventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MegaInventory</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index"> Add WareHouse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Add Client</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesOrder" asp-action="Index"> Add SalesOrder</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MegaInventory.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>